---
- name: Setup ML environment locally
  hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes

    - name: Install Python 3 and pip
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Copy app folder to /opt/ml
      copy:
        src: ../app/
        dest: /opt/ml/
        remote_src: no

    - name: Build Docker image
      shell: docker build -t fakenews-model /opt/ml

    - name: Run Docker container
      shell: docker run --rm -v /opt/ml/output:/opt/ml/output fakenews-model
