---
- name: Setup ML environment on remote machine
  hosts: all
  become: yes

  vars:
    app_dir: /opt/ml

  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes

    - name: Install Python 3 and pip
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Copy app folder contents to remote machine
      copy:
        src: ../app/
        dest: "{{ app_dir }}/"
        remote_src: no

    - name: Build Docker image
      shell: docker build -t fakenews-model {{ app_dir }}
      args:
        chdir: "{{ app_dir }}"

    - name: Run Docker container
      shell: docker run --rm -v {{ app_dir }}/output:/opt/ml/output fakenews-model
    #   args:
    #    chdir: "{{ app_dir }}"
    # - name: Install Python dependencies
    #   pip:
    #     requirements: "{{ app_dir }}/requirements.txt"
    #     executable: python3
    #   args:
    #     chdir: "{{ app_dir }}"
    # - name: Run the application
    #   shell: python3 app.py
    #   args:
    #     chdir: "{{ app_dir }}"
    #   async: 10
    #   poll: 0
